### ISSUE TITLE
Compatible?

### ISSUE THREAD

**Issue by DatOnePlayer** [AzhurniyBaklan/Metaglaphite#2]
Is this mod compatible to V6 yet?

**Comment by AzhurniyBaklan** [comment]
@DatOnePlayer, I know I am really late, but I don't plan on updating this mod for v6, since I generally don't understand it, at least for now. Maybe some time after official release I will make gears move, but there is a lot of content in my mod that needs rework for new source code. I will re-open this issue and tag you when I will draft a new release, if I even do it, obviously.

**Comment by AzhurniyBaklan** [comment]
@DatOnePlayer I have made a decision to stop developing this mod completely. It was fun to work with it when it was relevant, but now the times has changed and I moved to my new mod, which you can check right now from my profile.
